version: '3.4'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "ConfirmDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"

  webapi:
    image: confirmation_service:latest
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - "9901:80"
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - postgres
